version: '3'

services:

  prism:
    build:
      context: .
    volumes:
      - '.:/prism'
    ports:
      - "8001:8000"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - S3_BUCKET=tryprism-dev
      - S3_ENDPOINT_URL
      - AWS_REGION=us-east-1
      - TEST_IMAGE=images/test-1.jpg
      - DOMAIN=localhost
    env_file:
      - .env
