version: '3'

services:

  prism:
    build:
      context: .
    volumes:
      - '.:/prism'
    ports:
      - "8001:8000"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - MULTI_CUSTOMER_MODE
      - SECRETS_BUCKET
      - DEFAULT_CUSTOMER
      - AWS_REGION
      - TEST_IMAGE
      - DOMAIN
    env_file:
      - .env

  nginx:
      image: nginx:1.15.7
      depends_on:
        - prism
      volumes:
        - ./nginx-sample.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "5000:80"
