version: 2

jobs:
  linter:
    docker:
      - image: circleci/python:3.6.7-stretch
    steps:
      - checkout
      - run:
          command: |
            sudo pip install flake8
            flake8 .

  tests:
    docker:
      - image: circleci/python:3.6.7-stretch
    steps:
      - checkout
      - restore_cache:
            key: deps1-{{ checksum "requirements.txt" }}
      - run: pip install -r requirements.txt --user
      - save_cache:
          key: deps1-{{ checksum "requirements.txt" }}
          paths:
            - '/home/circleci/.local/bin'
            - '/home/circleci/.local/lib/python3.6/site-packages'
      - run:
          command: cd prism && python -m unittest

workflows:
  version: 2
  deployment:
    jobs:
      - tests:
          filters:
            branches:
              only:
                - main
